Unassigned users by mr skeleton fox
ITA-Dnipro/what-taqc pull request #29
Opened 2021-05-21 22:41 UTC by MrSkeletonFox

create WHAT_163, WHAT_172, WHAT_186

WHAT_172.java This test case verifies that the Administrator user can disable the Mentor by making DELETE request to the REST endpoint.
WHAT_163.java This test case verifies that Admin users can update information about mentors by making PUT
request to REST endpoint.
WHAT_186.java This test case verifies that Administrator can assign mentor role for unassigned account by making POST request to REST endpoint.

2021-05-22 03:38 UTC, BolsunovaNataliia approved these changes

2021-05-23 04:41 UTC, vl3xit commented on src/main/java/api_tests/mentor/WHAT_163.java
> +//        mapChanges.put("id", "115");
Remove commented code.

2021-05-23 04:42 UTC, vl3xit commented on src/main/java/api_tests/mentor/WHAT_163.java
> +//                and().body("id", equalTo(mapChanges.get("id"))).
Remove commented code.

2021-05-23 04:43 UTC, vl3xit requested changes
Remove commented code.

2021-05-23 16:36 UTC, valeriibahno approved these changes

2021-05-23 18:40 UTC, MashaLar approved these changes

2021-05-23 21:25 UTC, vl3xit approved these changes

2021-05-23 21:25 UTC, merged